from .animal_requests import get_all_animals
from .animal_requests import get_single_animal
from .location_requests import get_all_locations
from .location_requests import get_single_location
from .employee_requests import get_all_employees
from .employee_requests import get_single_employee
from .animal_requests import create_animal
from .employee_requests import create_employee
from .location_requests import create_location
